apiVersion: kapp.k14s.io/v1alpha1
kind: Config
waitRules:
- conditionMatchers:
  - type: ServiceAvailable
    status: "False"
    failure: true
  - type: ServiceAvailable
    status: "True"
    success: true
  resourceMatchers:
  - apiVersionKindMatcher:
      apiVersion: servicebinding.io/v1alpha3
      kind: ServiceBinding
---
apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: motd-backend-motd-config
  annotations:
    local-source-proxy.apps.tanzu.vmware.com: xploretanzu.azurecr.io/tap/tap-source-proxy:workload-ns-motd-backend@sha256:7f2a96d5ce2dc259bfabd598b7c49ace4a09ec414e84b1ad2cc4d0e3b8d397de
    autoscaling.knative.dev/maxScale: "3"
    autoscaling.knative.dev/metric: rps
    autoscaling.knative.dev/minScale: "0"
    autoscaling.knative.dev/target: "5"
    autoscaling.knative.dev/window: 120s
    kapp.k14s.io/change-group: servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: motd-backend
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    networking.knative.dev/visibility: cluster-local
    app.kubernetes.io/component: run
    carto.run/workload-name: motd-backend
spec:
  name: motd-config
  service:
    apiVersion: services.apps.tanzu.vmware.com/v1alpha1
    kind: ResourceClaim
    name: motd-backend-config
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: motd-backend

