apiVersion: kapp.k14s.io/v1alpha1
kind: Config
waitRules:
- conditionMatchers:
  - type: ServiceAvailable
    status: "False"
    failure: true
  - type: ServiceAvailable
    status: "True"
    success: true
  resourceMatchers:
  - apiVersionKindMatcher:
      apiVersion: servicebinding.io/v1alpha3
      kind: ServiceBinding
---
apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: motd-frontend-motd-config
  annotations:
    local-source-proxy.apps.tanzu.vmware.com: xploretanzu.azurecr.io/tap/tap-source-proxy:workload-ns-motd-frontend@sha256:5d742aab28e2c490e4a9622a4c62ea747d5d79cb2ee8cb1ef51a3f9e34679f0b
    autoscaling.knative.dev/maxScale: "3"
    autoscaling.knative.dev/metric: rps
    autoscaling.knative.dev/minScale: "0"
    autoscaling.knative.dev/target: "20"
    autoscaling.knative.dev/window: 60s
    kapp.k14s.io/change-group: servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: motd-frontend
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    networking.knative.dev/visibility: cluster-local
    app.kubernetes.io/component: run
    carto.run/workload-name: motd-frontend
spec:
  name: motd-config
  service:
    apiVersion: services.apps.tanzu.vmware.com/v1alpha1
    kind: ResourceClaim
    name: motd-frontend-config
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: motd-frontend

