apiVersion: apis.apps.tanzu.vmware.com/v1alpha1
kind: APIDescriptor
metadata:
  name: motd
  annotations:
    local-source-proxy.apps.tanzu.vmware.com: xploretanzu.azurecr.io/tap/tap-source-proxy:workload-ns-motd@sha256:c9aeb616b80727f3cff8dc8dcd2fda498f99b3677d0d77a6da51238cf68f48fc
    autoscaling.knative.dev/maxScale: "3"
    autoscaling.knative.dev/metric: rps
    autoscaling.knative.dev/minScale: "0"
    autoscaling.knative.dev/target: "100"
    autoscaling.knative.dev/window: 300s
  labels:
    apis.apps.tanzu.vmware.com/register-api: "true"
    app.kubernetes.io/part-of: motd
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: motd
spec:
  type: openapi
  description: MOTD API
  system: default/motd
  owner: default/motd-team
  location:
    path: /api/openapi
    baseURL:
      ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: motd

